### ISSUE TITLE
Install on Kibana 4.1?

### ISSUE THREAD

**Issue by saftle** [nreese/kibana-time-plugin#1]
Thanks for creating this plugin! How would one go about installing it with Kibana 4.1, since the plugin install method wasn't introduced until Kibana 4.2? I'm sadly limited to Kibana 4.1, since I'm using a Drupal module that is in turn limited to Elasticsearch 1.x ([Elasticsearch Connector](https://www.drupal.org/project/elasticsearch_connector)).

Thanks in advanced for any help.

**Comment by nreese** [comment]
I am not sure plugin installation is possible with 4.1. It looks like
kibana added the plugin framework with release 4.2. It looks like elastic
connector has a drupal module that supports elasticsearch 2.x so maybe
upgrading is an option.

Nathan

**Comment by saftle** [comment]
Thanks for responding! Yeah, sadly the version of the Elasticsearch Connector module that supports Elasticsearch 2.x is for Drupal 8 rather than Drupal 7. The site I'm working on currently is limited to Drupal 7 due to Drupal 8 being relatively new and not all modules, that are currently in use, have been updated yet.

**Comment by nreese** [comment]
Plugin can only support kibana 4.2 and up
