### ISSUE TITLE
How to use the plugin?

### ISSUE THREAD

**Issue by sreejithps303** [nreese/kibana-time-plugin#18]
Hi ,

I have installed the plugin and changed the packge.json to 5.2.1 (my version). But how to use it with kibana dashboards ? I am not getting any options

**Comment by TaurusD** [comment]
@sreejithps303 Hi, could you please tell me how did you install this plugin. 
I followed the instruction till the step `bower install`. It's said that bower is not a known command, and there is only a json file call bower.json, which can only be opened but not installed. 

Thank you! 

Also call @nreese for help. Thanks!

**Comment by nreese** [comment]
Install bower, https://bower.io/

**Comment by sreejithps303** [comment]
@TaurusD you can install npm directly  (yum install for linux and apt-get install  for Debian ) . then from npm module u can install bower (npm install -g bower ). Once you done it  you can use bower install command.

**Comment by sreejithps303** [comment]
@nreese I have installed the master version and followed the steps. Looks like the installation was successful. can you  help on how to invoke this in dashboards? elastic version is 5.1.2

**Comment by nreese** [comment]
In the kibana menu on the left, select `visualize`. Create a new visualization of type `Time widget`. Save the visualization. In the dashboard, add the time widget visualization just like any other visualization.

**Comment by sreejithps303** [comment]
@nreese  Great !! Thanks it works..
