### ISSUE TITLE
Kibana 5.5.2

### ISSUE THREAD

**Issue by Massim00** [nreese/kibana-time-plugin#22]
Hello,

thanks for a great plugin, unfortunately, i can't test it with latest available kibana version (5.5.2).
Is there a plans to support it in future?
Thanks.

**Comment by nreese** [comment]
The plan is to keep the plugin working with new kibana releases but its not a top priority. PRs would be greatly appreciated.

**Comment by MarnieGordon** [comment]
I'm also finding the incompatibility with 5.5.2. 
Any ETA on when it might be supported?

**Comment by nreese** [comment]
Did you follow the 5.5 installation instructions? What errors are you seeing?

I am able to run the plugin on 5.5 without any problems

**Comment by MarnieGordon** [comment]
Yes - I followed the 5.5 installation instructions. We're running in a Windows environment - maybe that is the difference?

**Comment by nreese** [comment]
Not sure. What errors are you getting on the kibana server? What errors are you getting in the browser console?

**Comment by MarnieGordon** [comment]
Reinstalling now - I had to remove it to get Kibana to start up. I'll follow up with error detail when installation is complete. Thanks for the support - this plugin has been a lifesaver for us!

**Comment by MarnieGordon** [comment]
I reinstalled on another dev instance, and it's working fine in version 5.5.2. I must have had a hiccup in the install process on the first box. Thanks.
