### ISSUE TITLE
Manual install of 5.5

### ISSUE THREAD

**Issue by Shifter2600** [nreese/kibana-time-plugin#24]
Is there a manual way to install the plugin? I am trying to get it working on the official Kibana Docker 5.6.1
I have my plugins folder volume outside the container and I am looking for a way to extract it directly into that folder on the host.

**Comment by nreese** [comment]
Unzip the release in the plugin folder. Delete everything under optimize/bundle and restart the kibana process.

**Comment by Shifter2600** [comment]
Seems there are missing files from the plugin .
Module not found: Error: Cannot resolve 'file' or 'directory' /usr/share/kibana/plugins/kibana-time-plugin/public/bower_components/bootstrap-addons/dist/css/bootstrap-addons.css in /usr/share/kibana/plugins/kibana-time-plugin/public\n     @ ./plugins/kibana-time-plugin/public/time.js 11:0-101\n    \n    ERROR in ./plugins/kibana-time-plugin/public/time.js\n    Module not found: Error: Cannot resolve 'file' or 'directory' /usr/share/kibana/plugins/kibana-time-plugin/public/bower_components/bootstrap-addons/dist/js/bootstrap-addons.js in /usr/share/kibana/plugins/kibana-time-plugin/public\n     @ ./plugins/kibana-time-plugin/public/time.js 13:0-99\n","error":{"message":"Optimizations failure.\n\n    \u001b[1m\u001b[31mERROR in ./plugins/kibana-time-plugin/public/time.js\n    Module not found: Error: Cannot resolve 'file' or 'directory' /usr/share/kibana/plugins/kibana-time-plugin/public/bower_components/bootstrap-addons/dist/css/bootstrap-addons.css in /usr/share/kibana/plugins/kibana-time-plugin/public\n     @ ./plugins/kibana-time-plugin/public/time.js 11:0-101\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in ./plugins/kibana-time-plugin/public/time.js\n    Module not found: Error: Cannot resolve 'file' or 'directory' /usr/share/kibana/plugins/kibana-time-plugin/public/bower_components/bootstrap-addons/dist/js/bootstrap-addons.js in /usr/share/kibana/plugins/kibana-time-plugin/public\n     @ ./plugins/kibana-time-plugin/public/time.js 13:0-99\u001b[39m\u001b[22m\n","name":"Error","stack":"Error: Optimizations failure.\n\n    \u001b[1m\u001b[31mERROR in ./plugins/kibana-time-plugin/public/time.js\n    Module not found: Error: Cannot resolve 'file' or 'directory' /usr/share/kibana/plugins/kibana-time-plugin/public/bower_components/bootstrap-addons/dist/css/bootstrap-addons.css in /usr/share/kibana/plugins/kibana-time-plugin/public\n     @ ./plugins/kibana-time-plugin/public/time.js 11:0-101\u001b[39m\u001b[22m\n    \n    \u001b[1m\u001b[31mERROR in ./plugins/kibana-time-plugin/public/time.js\n    Module not found: Error: Cannot resolve 'file' or 'directory' /usr/share/kibana/plugins/kibana-time-plugin/public/bower_components/bootstrap-addons/dist/js/bootstrap-addons.js in /usr/share/kibana/plugins/kibana-time-plugin/public\n     @ ./plugins/kibana-time-plugin/public/time.js 13:0-99\u001b[39m\u001b[22m\n\n    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:233:27)\n    at /usr/share/kibana/src/optimize/fs_optimizer.js:33:30\n    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:181:13)\n    at /usr/share/kibana/node_modules/webpack/lib/Compiler.js:403:12\n    at Compiler.next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)\n    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:40:4)\n    at Compiler.applyPluginsAsync (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:71:13)\n    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:400:9)\n    at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:577:13)\n    at Compilation.applyPluginsAsync (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:60:69)\n    at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:572:10)\n    at Compilation.next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)\n    at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:4)\n    at Compilation.applyPluginsAsync (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:71:13)\n    at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:567:9)\n    at Compilation.next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)\n    at ExtractTextPlugin.<anonymous> (/usr/share/kibana/node_modules/extract-text-webpack-plugin/index.js:303:4)\n    at Compilation.applyPluginsAsync (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:71:13)\n    at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:563:8)\n    at Compilation.next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)\n    at ExtractTextPlugin.<anonymous> (/usr/share/kibana/node_modules/extract-text-webpack-plugin/index.js:279:5)\n    at /usr/share/kibana/node_modules/async/lib/async.js:52:16"}}

**Comment by nreese** [comment]
you have to run `bower install` to fetch the dependencies

**Comment by Shifter2600** [comment]
So i have the files extracted on the host in /plugins the host is running docker and the container in docker has a volume mapped to /plugins.
Can bower install be ran outside the container on the host to prepare the /plugins/kibana-time-plugin?

**Comment by Shifter2600** [comment]
NM the last message I did the bower install on the Host and it all worked. Thx You can close this.
