### ISSUE TITLE
Consider as general Kibana enhancement

### ISSUE THREAD

**Issue by jccq** [nreese/kibana-time-plugin#25]
great work - very cool was wondering would this be too specific to propose as general kibana enhancement? (it would seem its right place would be in that panel possibly? or can this be set on any time variable?  
(sorry for abusing issues a bit here :) feel free to close)

**Comment by jccq** [comment]
or add as "input panel" ? :) https://github.com/elastic/kibana/pull/13314

**Comment by nreese** [comment]
@jccq There is an open issue for moving the time slider piece into kibana as an input control. https://github.com/elastic/kibana/issues/14177.

**Comment by jccq** [comment]
cool that covers it :) closing
