### ISSUE TITLE
Installed on 6.2 but I do not see the plugin in kibana

### ISSUE THREAD

**Issue by scadra** [nreese/kibana-time-plugin#32]
I have installed without error the plugin but I do not see the plugin in my kibana window

**Comment by jonathandick** [comment]
We would love to use this plugin (in fact, we will revert from 6.2 to the most recent supported Kibana version to be able to use it). Is there any plan to update to work with 6.2?

**Comment by soul3soul** [comment]
same here, used it in V5 and now on 6 ;(
Hoping itll be fixed

**Comment by nreese** [comment]
6.2 is not supported yet. No timeline on when it will be supported

**Comment by jonathandick** [comment]
Shoot but understand constraints on time. 

Is any Kibana 6.x version supported?

**Comment by soul3soul** [comment]
anyone knows a similar plugin?

**Comment by Shifter2600** [comment]
@soul3soul There is no other plugin. @jonathandick there is the 6.0  already listed

**Comment by nreese** [comment]
6.0 is supported

**Comment by jonathandick** [comment]
From what I can tell, the controls plugin was added in 6.1. We depend on this and would like to augment with this time plugin. This means going to 6.0 would not work.

We have a young developer who may be help transition. @nreese , do you have a sense of the complexity of making this plugin work for 6.2? Would you be willing to provide some mentorship?

**Comment by nreese** [comment]
I am not sure how complex the upgrade will be because I am not sure what is broken in 6.2. 

I will answer questions as best I can and will gladly accept a PR for upgrading to 6.2

**Comment by jonathandick** [comment]
Ok. Thank you, we will be in touch soon.

**Comment by thekofimensah** [comment]
I'm also interested in this!!

**Comment by michimau** [comment]
the plugin does work for me under 6.2.2.

**Comment by thekofimensah** [comment]
how did you get it to work? what steps did you take to get to work? I'd
love to know =)

**Comment by michimau** [comment]
just updated package.json, by setting https://github.com/nreese/kibana-time-plugin/blob/master/package.json#L3 to 6.2.2.

then business as usual:
bower install --force-latest
npm install

**Comment by nreese** [comment]
I have updated the readme with the 6.2 install instructions.

**Comment by thekofimensah** [comment]
I'm getting this error on 6.2.2:
```
Optimizations failure.\n   4299 modules\n    \n    \u001b[1m\u001b[31mERROR in /usr/share/kibana/plugins/kibana-time-plugin/public/time.js\n    
Module not found: Error: Can't resolve 'plugins/kibana-time-plugin/bower_components/bootstrap-addons/dist/css/bootstrap-addons.css'
 in '/usr/share/kibana/plugins/kibana-time-plugin/public
```
@nreese

**Comment by nreese** [comment]
Did you run the command `bower install`?

**Comment by thekofimensah** [comment]
Yep, when I run it:

```
bower cached        https://github.com/nreese/bootstrap-addons/files/851515/bootstrap-addons.zip#e-tag:8d3784242
bower validate      e-tag:8d3784242 against https://github.com/nreese/bootstrap-addons/files/851515/bootstrap-addons.zip#*
bower new           version for https://github.com/nreese/bootstrap-addons/files/851515/bootstrap-addons.zip#*
bower resolve       https://github.com/nreese/bootstrap-addons/files/851515/bootstrap-addons.zip#*
bower download      https://github.com/nreese/bootstrap-addons/files/851515/bootstrap-addons.zip
bower extract       bootstrap-addons#* bootstrap-addons.zip
bower resolved      https://github.com/nreese/bootstrap-addons/files/851515/bootstrap-addons.zip#e-tag:8d3784242
bower ENOTFOUND     Package option not found
```

**Comment by nreese** [comment]
Here is the output of a successful bower install
```
bower bootstrap-addons#*        cached https://github.com/nreese/bootstrap-addons/files/851515/bootstrap-addons.zip#e-tag:8d3784242
bower bootstrap-addons#*      validate e-tag:8d3784242 against https://github.com/nreese/bootstrap-addons/files/851515/bootstrap-addons.zip#*
bower bootstrap-addons#*           new version for https://github.com/nreese/bootstrap-addons/files/851515/bootstrap-addons.zip#*
bower bootstrap-addons#*       resolve https://github.com/nreese/bootstrap-addons/files/851515/bootstrap-addons.zip#*
bower bootstrap-addons#*      download https://github.com/nreese/bootstrap-addons/files/851515/bootstrap-addons.zip
bower bootstrap-addons#*       extract bootstrap-addons.zip
bower bootstrap-addons#*      resolved https://github.com/nreese/bootstrap-addons/files/851515/bootstrap-addons.zip#e-tag:8d3784242
bower bootstrap-addons#*       install bootstrap-addons#e-tag:8d3784242
```

What version of bower are you using? I am using `1.8.2`.

If you are still having problems with bower, then you could always manually extract the depenency. Extract the contents of [bootstrap-addons.zip](https://github.com/nreese/bootstrap-addons/files/851515/bootstrap-addons.zip) into the folder `kibana-time-plugin/public/bower_components/bootstrap-addons`

**Comment by thekofimensah** [comment]
Yeah I'm also on `1.8.2`... 

Just figured it out. Bower doesn't like to be run on root, but I have Kibana running as a service so to edit I need to be root. So I changed permissions of that folder and then bower install was successful. Thanks!

**Comment by ahmwahba** [comment]
Hi, I'm using kibana 6.2.4, I set the version in package.json to 6.2.4 and when I try npm install it says "kibana-time-plugin@6.2.4 No repository field" I also tried 6.2.2 but no success. any thoughts?

FYI: the time widget plugin is listed under visualize but I click it I get an error:  Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-05-29T00:16:59.606Z","oldVal":"2018-05-29T00:16:59.606Z"},{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs...

Please help.

Thanks.

**Comment by nreese** [comment]
@ahmwahba The dependencies are installed with `bower`, not npm. Run `bower install` to install dependencies.

**Comment by ahmwahba** [comment]
I ran bower install and it worked successfully. last line of the output is
bower bootstrap-addons#*       install bootstrap-addons#e-tag:8d3784242

but I still get the mentioned error when I click on the "time widget" under visualize section

**Comment by ahmwahba** [comment]
the last installation step in the README.md file: 
vi kibana-time-plugin/package.js //set version to match kibana version
what is package.js? is it package.json?

**Comment by nreese** [comment]
yes, there is a typo in the instructions
