### ISSUE TITLE
Quick Slide shows "undefined" options for Kibana 6.2

### ISSUE THREAD

**Issue by fatmali** [nreese/kibana-time-plugin#34]
Hey @nreese ,

Thanks for getting the plugin to work with the latest version of Kibana. We are having an issue trying to use the quick slide of the plugin because all the options read as "undefined". Here is a screenshot. Any help would be appreciated.

![test time widget - kibana clipular](https://user-images.githubusercontent.com/16671674/36720986-a700d338-1bba-11e8-91fd-a561f8d6d765.png)

**Comment by nreese** [comment]
Are you building from master? A PR as merged 12 hours ago that should have addressed this

**Comment by nreese** [comment]
There was a problem on master that has been resolved now. Should be working now

**Comment by gacekjr56** [comment]
Great thanks! Just confirmed that it works with Kibana 6.2.1.
