### ISSUE TITLE
Kibana 6.2.1 Crash

### ISSUE THREAD

**Issue by darklord1807** [nreese/kibana-time-plugin#37]
Hello,

I have installed plugin in Kibana 6.2.1 but it is crashing as soon as I am clicking on Visualization. 

![image](https://user-images.githubusercontent.com/9898518/40162603-8fedef02-59c5-11e8-9f25-dcacd7fe7438.png)

Kindly help, 
Thanks,
Naveesh

**Comment by nreese** [comment]
closing, duplicate of https://github.com/nreese/kibana-time-plugin/issues/39
