### ISSUE TITLE
kibana 6.2.4 Crasching when using kibana-time-plugin visualisation

### ISSUE THREAD

**Issue by retsuca** [nreese/kibana-time-plugin#39]
We recently upgraded our Elastic stack to 5.4.0 to 6.2.4 everything working smoothly, expect kibana-time-plugin.

When we installed as instructed. Kibana starts and discovery and our older dashboards works as expected. But when we try to open a dashboard which uses kibana-time-plugin visualisation, or when we try to create new kibana-time-plugin visualisation it throws an error and doesn't let us to continue.

I hope this information is enough.

Here  the error
`Error: Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting! Watchers fired in the last 5 iterations: [[{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"},{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"}],[{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"},{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"}],[{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"},{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"}],[{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"},{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"}],[{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"},{"msg":"fn: function(scope,locals,assign,inputs){var value=useInputs&&inputs?inputs[0]:parsedExpression(scope,locals,assign,inputs);return interceptorFn(value,scope,locals)}","newVal":"2018-06-12T21:00:00.000Z","oldVal":"2018-06-12T21:00:00.000Z"}]] http://errors.angularjs.org/1.6.5/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%2C%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%5D%2C%5B%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%2C%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%5D%2C%5B%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%2C%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%5D%2C%5B%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%2C%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%5D%2C%5B%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%2C%7B%22msg%22%3A%22fn%3A%20function(scope%2Clocals%2Cassign%2Cinputs)%7Bvar%20value%3DuseInputs%26%26inputs%3Finputs%5B0%5D%3AparsedExpression(scope%2Clocals%2Cassign%2Cinputs)%3Breturn%20interceptorFn(value%2Cscope%2Clocals)%7D%22%2C%22newVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%2C%22oldVal%22%3A%222018-06-12T21%3A00%3A00.000Z%22%7D%5D%5D (http://rapor.gsi365.com/bundles/vendors.bundle.js?v=16627:58) at window.onerror (http://rapor.gsi365.com/bundles/commons.bundle.js?v=16627:1:504052)`

**Comment by nitin0123** [comment]
I see the same error on Kibana 6.2.4, A dashboard with timepicker widget was working fine on an earlier version (6.2.2)

**Comment by nreese** [comment]
Try re-pulling from 6.2 branch. I have pushed a fix that will fix this problem
