### ISSUE TITLE
plugin doesn't support Kibana 6.3.0

### ISSUE THREAD

**Issue by gacekjr56** [nreese/kibana-time-plugin#40]
I'm facing problems to use plugin in latest 6.3.0 Kibana release
```
Module not found: Error: Can't resolve '@elastic/datemath' in '...\kibana\plugins\kibana-time-plugin\public'
```
I found that `datemath` imported in `timeController.js` was moved to different folder:
`@elastic/datemath` into `@kbn/datemath`
Thanks that I could start Kibana but after trying to use time-plugin I found other issues:
```
Error: Uncaught Error: [$injector:unpr] Unknown provider: timeUnitsProvider <- timeUnits <- KbnTimeVisController
http://errors.angularjs.org/1.6.9/$injector/unpr?p0=timeUnitsProvider%20%3C-%20timeUnits%20%3C-%20KbnTimeVisController (http://localhost:8085/bundles/vendors.bundle.js:8)
    at window.onerror (http://localhost:8085/bundles/commons.bundle.js:3:786868)
```

Could someone look closer on that?

**Comment by KaveriKrishnaKumar** [comment]
Same problem occured for me too

**Comment by door7302** [comment]
hello, 

I've got the same issue. Any plan to have an update for 6.3 ? Really appreciate. 

thks.

**Comment by rafaelcarsetimo** [comment]
+1

**Comment by kalstong** [comment]
+1

**Comment by nreese** [comment]
6.3 support has been added. https://github.com/nreese/kibana-time-plugin#kibana-63

**Comment by door7302** [comment]
Awesome... thks

**Comment by rafaelcarsetimo** [comment]
Nice! Thanks!

**Comment by kalstong** [comment]
Thks

**Comment by gacekjr56** [comment]
Verified that it works great. Thanks!

**Comment by KaveriKrishnaKumar** [comment]
Thanks

**Comment by KaveriKrishnaKumar** [comment]
Its not working for me … Please Help out

**Comment by nreese** [comment]
How is it not working? What errors are you getting and what steps did you take to get those errors? What does your environment look like?
