### ISSUE TITLE
Plugin issue with 6.6.0

### ISSUE THREAD

**Issue by conmurray** [nreese/kibana-time-plugin#47]
Hi there,

Just thought I'd share that it's not working with 6.6.0.
Im attaching the log file and I apologize for the format :/
I hope it can help. 
[text.log](https://github.com/nreese/kibana-time-plugin/files/2836280/text.log)

**Comment by conmurray** [comment]
Am I the only one who's tried this with 6.6.0 yet?

**Comment by EduardCR** [comment]
me too 
i tried and the kibana didnt start

**Comment by GustavoBellini** [comment]
Me too....

**Comment by RobinELM** [comment]
Hey,

After updating to quickly to 6.6, loosing the time-plugin was quite inconvenient ^^
By having a look at the Kibana starting error, it seems that the small changes mentioned in the pull request #49  have solved the problem for me.

**Comment by GustavoBellini** [comment]
> Ei,
> 
> Depois de atualizar rapidamente para o 6.6, perder o plug-in time foi bastante inconveniente ^^ 
> Ao dar uma olhada no erro inicial do Kibana, parece que as pequenas mudanças mencionadas no pedido pull [# 49](https://github.com/nreese/kibana-time-plugin/pull/49) resolveram o problema para mim.


Hello RobinElm,

I made the changes you mentioned in the request #49, but I did not succeed.
Kibana started, but the time-plugin icon does not appear in the new panel and what was working in the previous version stopped.

Note: I'm running version 6.6.1, released on February 19th.

**Comment by GustavoBellini** [comment]
> > Ei,
> > Depois de atualizar rapidamente para o 6.6, perder o plug-in time foi bastante inconveniente ^^
> > Ao dar uma olhada no erro inicial do Kibana, parece que as pequenas mudanças mencionadas no pedido pull [# 49](https://github.com/nreese/kibana-time-plugin/pull/49) resolveram o problema para mim.
> 
> Hello RobinElm,
> 
> I made the changes you mentioned in the request #49, but I did not succeed.
> Kibana started, but the time-plugin icon does not appear in the new panel and what was working in the previous version stopped.
> 
> Note: I'm running version 6.6.1, released on February 19th.


Excuse me, I forgot to change the kibana version in the packet.json file. I uninstalled the plugin, installed it again and ran normally. Thank you.

**Comment by nreese** [comment]
closed by https://github.com/nreese/kibana-time-plugin/pull/49
