### ISSUE TITLE
6.3 Installation in Kibana 6.5.4

### ISSUE THREAD

**Issue by kevininhub** [nreese/kibana-time-plugin#48]
We intend to install the plugin (6.3 branch) in kibana version 6.5.4, but kibana not start up normally like following, it is installed using "bower install". We guess it might relate to the tool.. May I know the version your using nodejs and apm to install the plugin?
 
Feb 11 00:30:41 localhost systemd[1]: Started Kibana.
Feb 11 00:30:41 localhost systemd[1]: Starting Kibana...
Feb 11 00:30:48 localhost kibana[1642]: {"type":"log","@timestamp":"2019-02-11T08:30:48Z","tags":["info","optimize"],"pid":1642,"message":"Optimizing and caching bundles for ml, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, space_selector, login, logout, dashboardViewer, apm, canvas, infra and kibana. This may take a few minutes"}
Feb 11 00:30:55 localhost kibana[1642]: Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`

**Comment by nreese** [comment]
You have to use master branch for 6.5 support at the moment. 6.3 branch does not support kibana 6.5

**Comment by kevininhub** [comment]
yes, we did use master branch, and came with this issue as well. Actually what we've done is install caniuse-lite and browserslist with npm and then copied them to KIBANA_HOME/node_modules folder, this seems fix the issue "Browserslist: caniuse-lite is outdated", but kibana is still hung at starting up.

**Comment by kevininhub** [comment]
yes, we used master branch, and came with this issue as well. What we've done is install caniuse-lite and browserslist with npm and then copied them to KIBANA_HOME/node_modules folder, this fixed the issue "run next command `npm update caniuse-lite browserslist`", but kibana is still hung at starting up ..
