### ISSUE TITLE
Add support for kibana 5.x

### ISSUE THREAD

**Issue by tianchao-haohan** [nreese/kibana-time-plugin#5]
As titled!

**Comment by ghost** [comment]
a zip exist for kibana 5.0 but after installation : 
`[warning] Plugin "kibana-time-plugin" was disabled because it expected Kibana version "0.0.1", and found "5.0.0".`

And it's work

**Comment by lmangani** [comment]
In Kibana 5 _(unfortunately, sadly, etc)_ the plugin version **MUST** match the Kibana version in `package.json`

Could you try as in PR https://github.com/nreese/kibana-time-plugin/pull/6

**Comment by nreese** [comment]
I have updated the install instructions for 5.0.0 and everything should work now
