### ISSUE TITLE
Add support for Kibana 5.0.X

### ISSUE THREAD

**Issue by GabrysCichy** [nreese/kibana-time-plugin#7]
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [kibana-time-plugin]. Expected [5.0.1]; found [5.0.0]

**Comment by lmangani** [comment]
@GabrysCichy this is a major annoyance with Kibana 5 forcing plugins to declare the exact version.
Try change the value of the "version" tag on the plugins ```package.json``` to your Kibana version

**Comment by nreese** [comment]
Update version in package.json to kibana version number
