### ISSUE TITLE
How to work in multiples dashboards

### ISSUE THREAD

**Issue by tianchao-haohan** [nreese/kibana-time-plugin#8]
![image](https://cloud.githubusercontent.com/assets/8639363/20821691/9ca791b4-b87f-11e6-8bd2-a8854d26bd7e.png)

From the attached picture, there are three dashboards in this page. I found that timepicker only take effect in the dashboard inside. So, how to use a global timepicker to effect all the dashbaords in a page? For example, use the uppermost timepicker to effect the below two dashboards.

**Comment by nreese** [comment]
Each embedded dashboard exists in an iframe. Javascript from one iframe cannot interact with javascript from another iframe.

I would recommend two solutions.
1) Put all visualizations into a single dashboard. That way you only have one iframe and one time picker.
2) Create your own time selection inputs outside of the iframe(s). When a new time is entered, update the iframe URLs to the newly updated time inputs.

Does that answer your question?

**Comment by tianchao-haohan** [comment]
@nreese Yes, I agree with you on the two solutions. 
Thanks!
